### ISSUE TITLE
[proposal] the save method should use "true" implicitly

### ISSUE THREAD

**Issue by renatoliveira** [ApexTestKit/ApexTestKit#16]
This proposal is to make the main ATK class to contain two `save` methods. One with a boolean in its signature (which is the one present today) and another one without parameters, that implies that the developer wants to save the records ("true" is used).

**Comment by inksword** [comment]
Hi @renatoliveira, thank you so much for the contribution. Just a second thought, probably I prefer to limit the APIs, and give the code more explicit behaviors, and avoid implicities. That's my initial intention to not include the `save()` API here.

**Comment by inksword** [comment]
Implicity will harm the readability, since the chances to use `save(false)` or `save(true)` are 50 to 50. And with a mockup service the most frequent use case is actually the `save(false)`, rather than the `save(true)`.

**Comment by renatoliveira** [comment]
I don't think it harms the readability. Salesforce's APIs also implement this kind of behavior (for example: the `Database.insert` method, with the `allOrNothing` parameter, which is assumed to be `true` for the method with just the records parameter). This way, it conforms to the platform's API style too. Wouldn't you agree?

**Comment by inksword** [comment]
Yes, I think it makes sense. `save()` should do what it intends to do by default. Good to have this discussed.
