### ISSUE TITLE
Get children list is empty when using save, save(false) or mock

### ISSUE THREAD

**Issue by DmitriyGeForce** [ApexTestKit/ApexTestKit#24]
After creating an object with children, object.childrens is empty.
For example:

        List<Account> accountMocks = (List<Account>) ATK.prepare(Account.SObjectType, 1)
                .field(Account.Name).repeat('Name')
                    .withChildren(Contact.SObjectType, Contact.AccountId, 1)
                .mock().get(Account.SObjectType);
        System.debug(accountMocks[0]);  //Account:{Name=Name, Id=001000zzzz00001AAA}
        System.debug(accountMocks[0].Contacts); //()

        List<Account> accountsSavedFalse = (List<Account>) ATK.prepare(Account.SObjectType, 1)
                .field(Account.Name).repeat('Name')
                    .withChildren(Contact.SObjectType, Contact.AccountId, 1)
                .save(false).get(Account.SObjectType);
        System.debug(accountsSavedFalse[0]); //Account:{Name=Name}
        System.debug(accountsSavedFalse[0].Contacts); //()

        List<Account> accountsSaved = (List<Account>) ATK.prepare(Account.SObjectType, 1)
                .field(Account.Name).repeat('Name')
                    .withChildren(Contact.SObjectType, Contact.AccountId, 1)
                .save().get(Account.SObjectType);
        System.debug(accountsSaved[0]); //Account:{Name=Name, Id=0011X00000jKZvoQAG}
        System.debug(accountsSaved[0].Contacts);    //()

**Comment by inksword** [comment]
@DmitriyGeForce Thank you for logging this issue, for discussion. For mock it is easier to support one level master-detail relationship, however to support multiple levels will require some more explorations. The background is that the children field is read-only, and can only be injected values via deserialization. To support children for mock is definitely the goal for next version, since the use case is very important.

For save, save(false), they are used as the same as when you construct sObjects list with code. Even you inserted the sObject with Database.insert, the children won't be retrieved automatically. We have to re-select the children relationship explicitly via SOQL.

**Comment by DmitriyGeForce** [comment]
@inksword Thank you for response and explanation. Can you tell me when the next version is planned?

**Comment by inksword** [comment]
@DmitriyGeForce Any preference from your side? I plan to have the next release in Jan next year 2021.

**Comment by DmitriyGeForce** [comment]
@inksword The only preference is to have this functionality in the nearest future)
It would be great to have this functionality at Jan next year 2021

**Comment by inksword** [comment]
@DmitriyGeForce Just some update to you, the children mock data support is at least 80% done.

Please wait a few more days, I need to write more test cases to cover mock scenarios. And there will be some paragraph in the Readme to describe what are the restrictions to generate children referencing. With all the computation logic added to the new algorithm, the performance goes down a bit. I also need to fine tune it.

Thus, more unit tests and performance are the two key areas I need to focus for now. According to [Salesforce documentation](https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_relationships_query_limits.htm#:~:text=No%20more%20than%2020%20parent,For%20example%2C%20Contact.), we probably only need to support 1 level of child referencing, with arbitrary levels (~5) parent referencing.

**Comment by DmitriyGeForce** [comment]
@inksword Great, thank you for an update. Look forward to using this functionality.

**Comment by inksword** [comment]
@DmitriyGeForce The feature you requested is released with v3.4. Please check the Readme for more detail.

**Comment by DmitriyGeForce** [comment]
@inksword Excellent, thank you for implementation!
