### ISSUE TITLE
Failing test_Util_Converter test case

### ISSUE THREAD

**Issue by Firtzberg** [ApexTestKit/ApexTestKit#35]
We're installed this package on our org. The test case test_Util_Converter is failing on [this](https://github.com/apexfarm/ApexTestKit/blob/4320f0dbb5387ee8b9fe1a2924d69e7dea38cae8/apex-test-kit/main/classes/ATKCoreTest.cls#L972) line.
It could be a timezone thing, since the default timezone is Chicago time.

```
Error message: | System.AssertException: Assertion Failed: Expected: 2021-01-16, Actual: 2021-01-15
-- | --
Stack trace: | Class.ATKCoreTest.test_Util_Converter: line 972, column 1
```

**Comment by inksword** [comment]
@Firtzberg Thanking for raising this issue. Just saw your message, I will try to look into it tonight, hope it doesn't impact your projects.

**Comment by Firtzberg** [comment]
What I've done locally is change [this line](https://github.com/apexfarm/ApexTestKit/blob/4320f0dbb5387ee8b9fe1a2924d69e7dea38cae8/apex-test-kit/main/classes/ATKCore.cls#L1720) to `return ((Datetime)input).formatGMT('yyyy-MM-dd');`

**Comment by inksword** [comment]
@Firtzberg Thank you again for raising this issue. Your suggestion has been applied to release v4.0.0. Please check the new BDD feature, happy hacking!
